name: hawkdove-env
dependencies:
- anaconda-client=1.2.1=py27_0
- appnope=0.1.0=py27_0
- backports_abc=0.4=py27_0
- binstar=0.12=2
- clyent=1.2.0=py27_0
- cycler=0.9.0=py27_0
- decorator=4.0.6=py27_0
- freetype=2.5.5=0
- future=0.15.2=py27_0
- ipykernel=4.1.1=py27_0
- ipython_genutils=0.1.0=py27_0
- ipywidgets=4.1.0=py27_0
- jinja2=2.8=py27_0
- jsonschema=2.4.0=py27_0
- jupyter=1.0.0=py27_1
- jupyter_client=4.1.1=py27_0
- jupyter_console=4.0.3=py27_0
- jupyter_core=4.0.6=py27_0
- libpng=1.6.17=0
- markupsafe=0.23=py27_0
- matplotlib=1.5.0=np110py27_0
- mistune=0.7.1=py27_0
- nbconvert=4.1.0=py27_0
- nbformat=4.0.1=py27_0
- notebook=4.0.6=py27_0
- numpy=1.10.2=py27_0
- openssl=1.0.2d=0
- pandas=0.17.1=np110py27_0
- path.py=8.1.2=py27_1
- pexpect=3.3=py27_0
- pickleshare=0.5=py27_0
- pip=7.1.2=py27_0
- ptyprocess=0.5=py27_0
- pygments=2.0.2=py27_0
- pyparsing=2.0.3=py27_0
- pyqt=4.11.4=py27_1
- python=2.7.11=0
- python-dateutil=2.4.2=py27_0
- python.app=1.2=py27_4
- pytz=2015.7=py27_0
- pyyaml=3.11=py27_1
- pyzmq=15.1.0=py27_0
- qt=4.8.7=1
- qtconsole=4.1.1=py27_0
- readline=6.2=2
- requests=2.9.0=py27_0
- setuptools=19.1.1=py27_0
- simplegeneric=0.8.1=py27_0
- singledispatch=3.4.0.3=py27_0
- sip=4.16.9=py27_0
- six=1.10.0=py27_0
- sqlite=3.8.4.1=1
- ssl_match_hostname=3.4.0.2=py27_0
- terminado=0.5=py27_1
- tk=8.5.18=0
- tornado=4.3=py27_0
- traitlets=4.0.0=py27_0
- wheel=0.26.0=py27_1
- yaml=0.1.6=0
- zeromq=4.1.3=0
- zlib=1.2.8=0
- pip:
  - astroid==1.3.8
  - backports-abc==0.4
  - backports.ssl-match-hostname==3.4.0.2
  - docutils==0.12
  - flask==0.10.1
  - flask-socketio==0.6.0
  - gdal==1.11.1
  - gevent==1.0.2
  - gevent-socketio==0.3.6
  - gevent-websocket==0.9.5
  - gnureadline==6.3.3
  - greenlet==0.4.9
  - instant-rst==0.9.1.2
  - ipython==4.0.1
  - ipython-genutils==0.1.0
  - itsdangerous==0.24
  - jupyter-client==4.1.1
  - jupyter-console==4.0.3
  - jupyter-core==4.0.6
  - logilab-common==1.0.2
  - pylint==1.4.4
  - rubber==1.2
  - werkzeug==0.10.4

